# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: slb-automation-4
# Description: automate slb servers for vThunder

terraform {
  required_version = ">= 0.13.0, < 0.15"
  required_providers {
    thunder = {
      source = "a10networks/thunder"
    }
  }
  backend "consul" {
    address = "10.65.22.163:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "thunder" {
  address  = var.thunder.address
  password = var.thunder.password
  username = var.thunder.username
}

# automate slb servers for vThunder
module "slb-automation-4" {
  source   = "/Users/asharma/Desktop/work/consul-nia/custom_module/terraform-thunder-service-group-sync-nia/"
  services = var.services

  virtual_servers = var.virtual_servers
}
