# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: slb-automation-4
# Description: automate slb servers for vThunder

thunder = {
  address  = "10.65.22.166"
  alias    = "thunder1"
  password = "a10"
  username = "admin"
}
